package droolsRule1;
import com.winnie.common.entity.QueryParam
import com.winnie.common.entity.ResultParam
import org.slf4j.LoggerFactory
import org.slf4j.Logger
import com.winnie.common.service.RuleDemoService


dialect "java"
rule "rule11"
   salience 99
    //如果when这里有两个入参，则需要kieSession同时insert这两个参数才会触发引擎
   when queryParam: QueryParam(paramSign!= null && paramSign.equals("+"))
         ruleDemoService: RuleDemoService()
         resultParam: Integer()
   then
          final Logger LOGGER = LoggerFactory.getLogger("加法 规则引擎1");
          LOGGER.info("参数:param1="+queryParam.getParam1()+ ", param2="+queryParam.getParam2()+"; paramSign="+queryParam.getParamSign());
          resultParam = ruleDemoService.addParam(queryParam);
          queryParam.setResult(resultParam);
end

rule "rule12"
    salience 98
    when queryParam: QueryParam(paramSign!= null && paramSign.equals("-"))
          ruleDemoService: RuleDemoService()
    then
         final Logger LOGGER = LoggerFactory.getLogger("减法 规则引擎1");
         LOGGER.info("参数:param1="+queryParam.getParam1()+ ", param2="+queryParam.getParam2()+"; paramSign="+queryParam.getParamSign());
         queryParam.setResult(ruleDemoService.subParam(queryParam));
 end