package droolsRule2;
import com.winnie.droolsruleconfig.entity.QueryParam
import com.winnie.droolsruleconfig.entity.ResultParam
import org.slf4j.LoggerFactory
import org.slf4j.Logger
import com.winnie.droolsruleconfig.service.RuleDemoService
import com.winnie.droolsruleconfig.service.RuleDemoServiceImpl ;


dialect "java"
rule "rule11"
   salience 99
    //如果when这里有两个入参，则需要kieSession同时insert这两个参数才会触发引擎
   when queryParam: QueryParam(paramSign!= null && paramSign.equals("+"))
         ruleDemoService: RuleDemoService()
         resultParam: Integer()
   then
          final Logger LOGGER = LoggerFactory.getLogger("加法 规则引擎1");
          LOGGER.info("参数:param1="+queryParam.getParam1()+ ", param2="+queryParam.getParam2()+"; paramSign="+queryParam.getParamSign());
          resultParam = ruleDemoService.addParam(queryParam);
          queryParam.setResult(resultParam);
end

rule "rule21"
    salience 98
    when queryParam: QueryParam(paramSign!= null && paramSign.equals("-"))
          ruleDemoService: RuleDemoService()
    then
         final Logger LOGGER = LoggerFactory.getLogger("减法 规则引擎1");
         LOGGER.info("参数:param1="+queryParam.getParam1()+ ", param2="+queryParam.getParam2()+"; paramSign="+queryParam.getParamSign());
         queryParam.setResult(ruleDemoService.subParam(queryParam));
 end


 rule "rule31"
    salience 96
    when queryParam: QueryParam(paramSign!= null && paramSign.equals("*"))
          ruleDemoService: RuleDemoService()
          resultParam: ResultParam()
    then
           final Logger LOGGER = LoggerFactory.getLogger("乘法 规则引擎1");
           LOGGER.info("参数:param1="+queryParam.getParam1()+ ", param2="+queryParam.getParam2()+"; paramSign="+queryParam.getParamSign());
           resultParam.setResult(ruleDemoService.mulParam(queryParam));
 end


 rule "rule41"
     salience 95
     when queryParam: QueryParam(paramSign!= null && paramSign.equals("/"))
           ruleDemoService: RuleDemoService()
           resultParam: ResultParam()
     then
          final Logger LOGGER = LoggerFactory.getLogger("除法 规则引擎1");
          LOGGER.info("参数:param1="+queryParam.getParam1()+ ", param2="+queryParam.getParam2()+"; paramSign="+queryParam.getParamSign());
          resultParam.setResult(ruleDemoService.divParam(queryParam));
  end